name: CI/CD with terraform
on:
  push:
    branches:
      - master

env:
  AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID 
  AWS_ACCESS_KEY_SECRET: AWS_ACCESS_KEY_SECRET 
  TF_STATE_BUCKET_NAME: AWS_STATE_BUCKET_NAME 
  AWS_SSH_KEY_PRIVATE: AWS_SSH_KEY_PRIVATE 
  AWS_SSH_KEY_PUBLIC: AWS_SSH_KEY_PUBLIC 
  AWS_REGION: us-east-1

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: $secrets.AWS_ACCESS_KEY_ID
          aws-secret-access-key: $secrets.AWS_ACCESS_KEY_SECRET
          aws-region: us-east-1    
      - name: terraform init
        run: terraform init -migrate-state -backend-config="bucket=$TF_STATE_BUCKET_NAME" -backend-config="region=us-east-1"
        working-directory: ./terraform
      - name: Terraform Plan
        id: plan
        run: |-
          terraform plan \
          -var="region=us-east-1" \
          -var="public_key=$PUBLIC_SSH_KEY" \
          -var="private_key=$PRIVATE_SSH_KEY" \
          -var="key_name=$deployer-key" \
          -out=PLAN
        working-directory: ./terraform
      - name: Terraform Apply
        id: apply
        run: terraform apply PLAN
        working-directory: ./terraform 
